<?php

namespace Client\PlanningBundle\Repository;

/**
 * WeeksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeeksRepository extends \Doctrine\ORM\EntityRepository
{
}
