<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC7saz6f\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC7saz6f/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerC7saz6f.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerC7saz6f\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerC7saz6f\appDevDebugProjectContainer([
    'container.build_hash' => 'C7saz6f',
    'container.build_id' => '10a6b949',
    'container.build_time' => 1569852729,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC7saz6f');
