<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxrnlsj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxrnlsj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVxrnlsj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVxrnlsj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVxrnlsj\appDevDebugProjectContainer([
    'container.build_hash' => 'Vxrnlsj',
    'container.build_id' => '85ed945a',
    'container.build_time' => 1570803974,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVxrnlsj');
